name: ğŸš€ Deploy Cartify Backend to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Ø£ÙŠ push Ø¹Ù„Ù‰ main = deploy

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: ğŸ§± Checkout repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./Cartify.API/Cartify.API.csproj


      - name: ğŸ§© Build
        run: dotnet build --configuration Release --no-restore

      - name: ğŸš€ Publish
        run: dotnet publish -c Release -o ./publish

      - name: â˜ï¸ Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.APPLICATION_NAME }}
          environment_name: ${{ secrets.ENVIRONMENT_NAME }}
          version_label: ${{ github.run_number }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: ./publish
